# Generated by Django 4.1.4 on 2024-02-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_delete_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu'},
        ),
    ]
