# Generated by Django 5.0.7 on 2024-07-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
