# Generated by Django 5.0.7 on 2024-07-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_category_slug_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='creatorId',
            field=models.IntegerField(default=0),
        ),
    ]
